# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Daniel Trejo
title: Sysadmin Sr. | DevOps & Cloud Engineer
email: luisdanieltrejo@gmail.com
website: https://luisdanieltrejo.github.io/

# Dark Mode
darkmode: false

# Social links
twitter_username: luisdtrejosh
github_username: luisdanieltrejo
instagram_username: luisdtrejosh
linkedin_username: luisdanieltrejo

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Administrador de Sistemas Senior con más de 15 años de experiencia en infraestructura IT, entornos Windows y Linux, virtualización y cloud. 
  Experto en administración de servidores, redes y seguridad, con foco en automatización (PowerShell, Bash, Ansible) y continuidad operativa.
  Experiencia liderando proyectos regionales en Latinoamérica y Estados Unidos en inglés avanzado, gestionando datacenters críticos y optimizando plataformas híbridas.
  Actualmente orientado a evolución profesional hacia DevOps y Cloud Engineering.

content:
  - title: Experiencia
    layout: list
    content:
      - layout: left
        title: Team Quality
        link: https://www.teamquality.com.ar
        sub_title: Analista de Infraestructura Sr.
        caption: Ene 2024 - Presente
        description: |
          - Administración de servidores Windows/Linux y firewalls en entornos críticos.
          - Implementación de políticas de backup y automatización con PowerShell y Ansible, reduciendo un 40% las tareas manuales.
          - Gestión de proyectos de ciberseguridad, mitigando vulnerabilidades críticas.
          - Optimización de disponibilidad y seguridad en infraestructura.

      - layout: left
        title: Enerflex (antes Exterran)
        link: https://www.enerflex.com
        sub_title: Analista de Sistemas Sr.
        caption: May 2013 - Dic 2023
        description: |
          - Responsable del centro de datos principal de Latinoamérica (top 3 global).
          - Administración de infraestructura IT: servidores, redes y virtualización (VMware, Hyper-V).
          - Implementación de políticas de disaster recovery con Veeam (RPO < 4h, RTO < 2h).
          - Reducción de incidentes críticos en un 30% mediante automatización de monitoreo.
          - Lideré proyectos de infraestructura para Argentina, México, Colombia y Estados Unidos.

      - layout: left
        title: Software del Plata
        link: https://ar.linkedin.com/company/software-del-plata
        sub_title: Soporte IT / Administrador de Redes
        caption: May 2007 - Ene 2008 / Feb 2008 - Dic 2011
        description: |
          - Soporte IT on-site para OSDE, Aerolíneas Argentinas y DHL.
          - Administración de redes y enlaces de datos a nivel nacional.
          - Monitoreo y mejora de sitios remotos, garantizando disponibilidad y continuidad.

  - title: Certificaciones y Educación
    layout: list
    content:
      - layout: left
        title: Oracle Cloud Infrastructure Foundations 2021 Associate
        caption: 2021
        description: |
          Certificación oficial de Oracle Cloud, validando conocimientos en fundamentos de cloud computing, IAM, networking y servicios básicos.

      - layout: left
        title: Diplomatura en Ciberseguridad
        caption: [Año]
        description: |
          Formación orientada a seguridad de la información, identificación de riesgos, mitigación de vulnerabilidades y cumplimiento de estándares.

  - title: Habilidades Técnicas
    layout: text
    content: |
      **Sistemas Operativos:** Windows Server, Rocky Linux, Ubuntu, RHEL  
      **Virtualización e Infraestructura:** VMware vSphere/ESXi, Hyper-V, Veeam Backup  
      **Cloud Computing:** Oracle Cloud (certificado), AWS (EC2, S3, IAM), Azure (AD, Networking)  
      **Automatización y Scripting:** PowerShell, Bash, Ansible, Terraform  
      **Redes y Seguridad:** Firewalls, VPN, AD, PKI, Hardening, Compliance  
      **Monitoreo y Gestión:** Zabbix, Nagios, Grafana, Prometheus  

  - title: Idiomas
    layout: text
    content: |
      - Español: Nativo  
      - Inglés: Avanzado (C1) – comunicación fluida en entornos internacionales, 10+ años trabajando con equipos de Estados Unidos  

  - title: Proyectos Destacados
    layout: list
    content:
      - layout: left
        title: Migración a infraestructura híbrida cloud
        caption: Enerflex
        description: |
          Migración de más de 100 VMs en VMware hacia infraestructura híbrida, logrando una reducción del 25% en costos.

      - layout: left
        title: Automatización de parches
        caption: Team Quality
        description: |
          Implementación de automatización de parches en Windows y Linux, reduciendo en 70% los tiempos de despliegue.

      - layout: left
        title: Hardening de servidores
        caption: Enerflex
        description: |
          Endurecimiento de servidores productivos siguiendo lineamientos CIS Benchmarks.

  - title: ¿En que estoy trabajando?
    layout: list
    content:
      - layout: left
        title: XDR Wazuh
#        caption: Enerflex
        description: |
          Migración de más de 100 VMs en VMware hacia infraestructura híbrida, logrando una reducción del 25% en costos.

      - layout: left
        title: Hardening Windows & Linux
#        caption: Team Quality
        description: |
          Implementación de automatización de parches en Windows y Linux, reduciendo en 70% los tiempos de despliegue.

      - layout: left
        title: Migracion PRTG a Zabbix
#        caption: Enerflex
        description: |
          Endurecimiento de servidores productivos siguiendo lineamientos CIS Benchmarks.


# Footer
footer_show_references: true
references_title: Referencias disponibles a solicitud

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
